### ISSUE TITLE
Validate Epson V850

### ISSUE THREAD

**Issue by local-minimum** [Scan-o-Matic/scanomatic-standalone#158]
# 📋 Info

Make sure it is compatible with SoM

# 🏁 DoD

- [x] Can perform scan in transparency mode using the same dimensions and resolution
```
        SCAN_MODES.TPU: {
            SCAN_FLAGS.Source: "Transparency",
            SCAN_FLAGS.Format: "tiff",
            SCAN_FLAGS.Resolution: "600",
            SCAN_FLAGS.Mode: "Gray",
            SCAN_FLAGS.Left: "0",
            SCAN_FLAGS.Top: "0",
            SCAN_FLAGS.Width: "203.2",
            SCAN_FLAGS.Height: "254",
            SCAN_FLAGS.Depth: "8",
        },
```
- [x] Can be made so that it doesn't turn itself off or goes into sleep-mode / always accessible computer over the range of days.
(Previous hardware hack forces power button to always be pressed)

**Comment by local-minimum** [comment]
I'm not sure what tests have been done so I made this issue to have it tracked.

**Comment by joakimmoller** [comment]
The v850 scanner identify itself as a v800. Can scan with same options. same same.

**Comment by local-minimum** [comment]
fyi it always accepted those parameters, the image must be validated to match the settings
