### ISSUE TITLE
'should render an <AnimatedProgressBar />'

### ISSUE THREAD

**Issue by skymandr** [Scan-o-Matic/scanomatic-standalone#70]
# 📋 Info

There is an empty test in `PlateEditor.test.jsx` with the description `xit('should render an <AnimatedProgressBar />'` (note the `x` in `xit`) which causes the test-runner to skip it and saying so in the report.

# 🏁 DoD

- [ ] Either remove it (if it isn't applicable),
- [ ] or implement it (if it is)

**Comment by local-minimum** [comment]
Remove it, there's no `AnimatedProgressBar` as far as I can see.
